### PR TITLE
Remove the art lib from our nuget pack command

### PR DESCRIPTION
**Pull request by HeyImChris**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [x] I am making a change required for Microsoft usage of react-native

## Summary

Art is removed so we can't pack what doesn't exist

## Changelog

[Fix] [Bug] - Remove art lib from nuget pack

## Test Plan

We can validate in the CI by seeing if the nuget pack gets past the art library.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-macos/pull/600)

### CODE REVIEW

**Review by acoates-ms — APPROVED** [review]

**Comment by acoates-ms** [comment]
Does that need to go in the 0.62 branch too?  And do we still use the nuspec from here?  Shouldn't we move that internally?

**Review by harrieshin — APPROVED** [review]

**Comment by HeyImChris** [comment]
> Does that need to go in the 0.62 branch too? And do we still use the nuspec from here? Shouldn't we move that internally?

Should go into 62 for sure. You're saying you want the whole nuspec moved internally?

**Comment by acoates-ms** [comment]
yeah.  Maybe not right now, but there doesn't seem to me to be any point in it needing to be in this repo.

**Comment by HeyImChris** [comment]
> yeah. Maybe not right now, but there doesn't seem to me to be any point in it needing to be in this repo.

Cool yea same page there though. It's definitely internal

**Pull request merged**
