### PR TITLE
Fix RCTPlatformDisplayLink runloop modes

### PR DESCRIPTION
**Pull request by christophpurrer**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

The `_modes` added to the display link were being ignored in favor of always running on `kCFRunLoopDefaultMode`. This would cause animations to not run when in `NSEventTrackingRunLoopMode`, which is a member of `NSRunLoopCommonModes`. This fixes that by passing the `_modes` into `CFRunLoopPerformBlock`, which does accept an array:

> A CFString that identifies a runloop mode, or a CFArray of CFStrings that each identify a runloop mode.

This also protects `_runloop` and `_modes` with the existing spin lock that is meant to protect them (see the `invalidate` method below).

Reviewed By: lyahdav

Differential Revision: D27721006

## Changelog

[macOS] [Fixed] - Pass in correct runLoopMode in RCTPlatformDisplayLink

## Test Plan

Fixes long press on selectable text (in Messenger Desktop):

### CODE REVIEW

**Comment by Saadnajmi** [comment]
A dumb question: I noticed that while an NSMenu is open, React Native stops running / event processing (i.e: mouseEnter/Exit events aren't sent, and a console.log set to run every 1 second won't fire. Over you close the menu, all the console.logs that didn't fire, fire at once).

I figured that was because the run loop of the NSMenu took priority. Would this change have any effect on that?

**Review by HeyImChris — APPROVED** [review]

**Comment by christophpurrer** [comment]
@Saadnajmi  > If you have a good repro scenario > can you just try it out with and w/o my change?

**Comment by Saadnajmi** [comment]
> @Saadnajmi > If you have a good repro scenario > can you just try it out with and w/o my change?

Just tested it, and the run loop doesn't seem blocked when an NSMenu is open anymore! That's a huge deal to me, thank you!

**Comment by christophpurrer** [comment]
2 birds - 1 stone ;-)

**Pull request merged**
