### PR TITLE
Add MultilineTextInput drag/drop support

### PR DESCRIPTION
**Pull request by christophpurrer**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

This allows `MultilineTextInput` to also accept and respond to the same drag and drop props as `View` (and as SingleLineTextInput) which is discussed here https://github.com/microsoft/react-native-macos/issues/842

## Changelog

[macOS] [Added] - Add MultilineTextInput drag/drop support

## Test Plan

Using this customized example from https://github.com/microsoft/react-native-macos/blob/main/packages/rn-tester/js/examples/Touchable/TouchableExample.js#L523-L538
```
          <TouchableOpacity
            style={styles.wrapper}
            testID="touchable_feedback_mouse_events_button"
            accessibilityLabel="touchable feedback mouse events"
            onPressIn={e => this._appendEvent('MouseIn', e.nativeEvent)}
            onPressOut={e => this._appendEvent('MouseOut', e.nativeEvent)}
            draggedTypes={'fileUrl'}
            onDragEnter={e =>
              this._appendEvent('TouchableOpacityEnter', e.nativeEvent)
            }
            onDragLeave={e =>
              this._appendEvent('TouchableOpacityLeave', e.nativeEvent)
            }
            onDrop={e => this._appendEvent('TouchableOpacityDrop', e.nativeEvent)}
            >
            <Text style={styles.button}>Click Me</Text>
          </TouchableOpacity>
          <TextInput
            multiline={false}
            draggedTypes={'fileUrl'}
            onDragEnter={e =>
              this._appendEvent('SinglelineEnter', e.nativeEvent)
            }
            onDragLeave={e =>
              this._appendEvent('SinglelineLeave', e.nativeEvent)
            }
            onDrop={e => this._appendEvent('SinglelineDrop', e.nativeEvent)}            
            style={{height: 40, width: 500, marginTop: 20}}
            placeholder="SINGLE LINE"
          />
          <TextInput
            multiline={true}
            draggedTypes={'fileUrl'}
            onDragEnter={e =>
              this._appendEvent('MultilineEnter', e.nativeEvent)
            }
            onDragLeave={e =>
              this._appendEvent('MultilineLeave', e.nativeEvent)
            }
            onDrop={e => this._appendEvent('MultilineDrop', e.nativeEvent)}               
            style={{height: 40, width: 500, marginTop: 20}}
            placeholder="MULTI LINE"
          />
```

Before

https://user-images.githubusercontent.com/484044/184041077-751ad57d-a2d1-4a0f-896f-77b75970487a.mov

After

https://user-images.githubusercontent.com/484044/184041068-a39012d8-d5fc-43cc-8c57-4aa60c7cd07c.mov

### CODE REVIEW

**Review by Saadnajmi — APPROVED** [review]
(I should really add those props to Pressable one day...)

**Comment by Saadnajmi** [comment]
Could you actually add that test page to RN-Tester? And if you don't specify `onDragEnter/Leave` as callbacks, what happens? Do you get the previous behavior of just getting the file URL?

**Comment by christophpurrer** [comment]
I have added an example for the TextInput.example on macOS

The behavior is the same before (only the example w/o the native changes)

https://user-images.githubusercontent.com/484044/186337270-0fc51d1e-c095-4489-830d-f09832785f85.mov

and after my native code changes

https://user-images.githubusercontent.com/484044/186337321-3192881d-c01f-4f05-9bf4-3f15df011a49.mov

JFYI: Drag/Drop partially works for SingleLineTextInputs only even w/o my changes as it piggy bags on the RCTView handler ...

**Comment by Saadnajmi** [comment]
I guess this one has conflicts now?

**Comment by christophpurrer** [comment]
rebased ...

**Comment by Saadnajmi** [comment]
I'm seeing some strange behavior when a SingleLine TextInput has keyboard focus. If I drag a file over. then both `Enter` and `Leave` are called in quick succession. Would you happen to know why?

https://user-images.githubusercontent.com/6722175/189054132-dd68f20d-5008-485b-9264-9f14352d3098.mov

**Comment by christophpurrer** [comment]
> I'm seeing some strange behavior when a SingleLine TextInput has keyboard focus. If I drag a file over. then both `Enter` and `Leave` are called in quick succession. Would you happen to know why?
> 
>  Screen.Recording.2022-09-07.at.11.48.55.PM.mov

I don't
This is actually and existing issue and not changed with this PR.
Just try out the example w/o the native changes here.

SingleLineTextFields on macOS are just different (immature?) compared to MultilineTextFields, because one is based on NSTextField and the other on NSTextView

**Pull request merged**
