### PR TITLE
[0.68] Refactor how focusable is handled in RCTView

### PR DESCRIPTION
**Pull request by Saadnajmi**
Copy of #1437 into 0.68-stable

### CODE REVIEW

**Review by lyzhan7 — APPROVED** [review]

**Review by mischreiber — APPROVED** [review]

**Review by chiuam — APPROVED** [review]

**Comment by lyzhan7** [comment]
This PR looks slightly different from the original one, do you need the [self.layer setPDisplay] line for 0.68?

**Comment by Saadnajmi** [comment]
> self.layer setPDisplay

Where do you see that line? Might be a difference between our `main` branch and our `[0.68-stable]` branch. The former generally has more commits.

**Comment by lyzhan7** [comment]
> > self.layer setPDisplay
> 
> Where do you see that line? Might be a difference between our `main` branch and our `[0.68-stable]` branch. The former generally has more commits.

First change here

Screen Shot 2022-10-26 at 10 41 27 AM

**Comment by Saadnajmi** [comment]
> > > self.layer setPDisplay
> > 
> > 
> > Where do you see that line? Might be a difference between our `main` branch and our `[0.68-stable]` branch. The former generally has more commits.
> 
> First change here
> 
> Screen Shot 2022-10-26 at 10 41 27 AM

Oh no... `setPDisplay` was a typo that shouldn't have made it in 😅

Gonna go fix that now....

**Pull request merged**
