### PR TITLE
Update macOS init template to enable New Architecture

### PR DESCRIPTION
**Pull request by shwanton**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

**The default template was never upgraded to 0.71 and was not loading the new arch when `RCT_NEW_ARCH_ENABLED=1` flag was passed to `pod install`

This PR picks #1853 to main

## Changelog

[MACOS] [FIXED] - Update macOS init template to enable New Architecture

## Test Plan

See test plan in #1853

### CODE REVIEW

**Review by Saadnajmi — APPROVED** [review]

**Comment by xysun** [comment]
This PR sets the macos app size under RCT to be a fixed 1024x768 ([code](https://github.com/microsoft/react-native-macos/blob/7b5c55d05f38684695c8050ddaf7e4de6bdf30e0/Libraries/AppDelegate/RCTAppDelegate.mm#L82)), is there anyway I can override this number?

@Saadnajmi @shwanton  thank you.

**Comment by Saadnajmi** [comment]
> This PR sets the macos app size under RCT to be a fixed 1024x768 ([code](https://github.com/microsoft/react-native-macos/blob/7b5c55d05f38684695c8050ddaf7e4de6bdf30e0/Libraries/AppDelegate/RCTAppDelegate.mm#L82)), is there anyway I can override this number?
> 
> I tried update `self.window` in `applicationDidFinishLaunching` but all it did was open a new window with no view, the original view stays the same size.
> 
> ```
> NSScreen *screen = [NSScreen mainScreen];
>   NSRect screenFrame = [screen visibleFrame];
>   NSWindow *window = [[NSWindow alloc] initWithContentRect:screenFrame
>                                                   styleMask:NSWindowStyleMaskTitled
>                                                     backing:NSBackingStoreBuffered
>                                                       defer:NO];
> 
>   [window makeKeyAndOrderFront:nil];
>   self.window = window;
> ```
> 
> @Saadnajmi @shwanton  thank you.

To be clear, the window is not resizable? And you can't programmatically access the window/ set the frame afterwards?

**Comment by xysun** [comment]
The window is resizable. However I want to set the window size to screen size upon launch, I tried to set the frame in appdelegate: 

```
NSScreen *screen = [NSScreen mainScreen];
  NSRect screenFrame = [screen visibleFrame];
  self.window.contentViewController.view.frame = screenFrame;
  [self.window setFrame:screenFrame display:YES];
```

This builds but doesn't change the launch window size though; I also tested using a 800x600 rect to make sure it's not a problem with `mainScreen` and that didn't work either.

**Comment by Saadnajmi** [comment]
I see, ideally the user can specify their frame in their app, rather than our hardcoded default. To that end, I think the intention is RCTAppDelegate's `createRootViewController` method is the entry point for that. If the code was refactored so that instead of us hardcoding the constant, it came from the view controller (that you can override) would that work? Feel free to also submit a PR if that does!

**Pull request merged**
