### PR TITLE
Disable hermes in RNTester Podfile

### PR DESCRIPTION
**Pull request by Saadnajmi**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

RNTester-macOS did not build on an m1 Mac for arm64. The build errors implied there was a problem with Hermes. Disabling Hermes leads to a successful build.

## Changelog

[macOS] [Fixed] - Fixed building RNTester on ARM64 by disabling hermes

## Test Plan

Built and ran RNTester-macOS on my m1 Mac mini with arm64 and not rosetta.

### CODE REVIEW

**Comment by Saadnajmi** [comment]
The type of errors seen without disabling: 
e6abbbf1-2a8a-49b6-8819-a8e983aa8bbd

**Comment by harrieshin** [comment]
can we make sure we have a ticket to track Hermes would need to support m1 machines properly?

**Review by harrieshin — APPROVED** [review]

**Comment by Saadnajmi** [comment]
> can we make sure we have a ticket to track Hermes would need to support m1 machines properly?

Would that be an issue in this repo, or the hermes repo? Not sure if hermes explicitly supports RN-macOS or we just kinda got it for free. @HeyImChris in case he knows best place to track

**Comment by Saadnajmi** [comment]
Filed #781 to track publicly

**Pull request merged**
