### PR TITLE
VirtualizedList accounts for components other than ScrollView and does not throw on _scrollRef.scrollTo calls

### PR DESCRIPTION
**Pull request by pavelchern**
#### Please select one of the following
- [x] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [ ] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary
According to the absolutely right comment
"Note that `this._scrollRef` might not be a `ScrollView`" that is already in the codebase `this._scrollRef.scrollTo` can not always be called directly.
This was already fixed in the https://github.com/facebook/react-native/blob/master/Libraries/Lists/VirtualizedList.js#L373 
Adding safeguard-checks for all the places where `_scrollRef.scrollTo()` is called.
This problem was spotted when some components using VirtualizedList in some conditions started to fail in runtime.
Digging deeper it became apparent that it is a bug inside VirtualizedList and it was already fixed in Facebook's RN implementation

## Changelog

[JavaScript] [Fixed] - Adding safeguard-checks for all the places where `_scrollRef.scrollTo()` is called directly without checks that it is supported by the underlaying component

## Test Plan

The runtime error 
`TypeError: this._scrollRef.scrollTo is not a function. (In 'this._scrollRef.scrollTo(r?{x:p,animated:s}:{y:p,animated:s})', 'this._scrollRef.scrollTo' is undefined` 
is probably easiest to reproduce if VirtualizedList is passed the custom `renderScrollComponent` that does not have `scrollTo` implementation. With this change it won't cause the runtime error but 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-macos/pull/532)

### CODE REVIEW

**Comment by alloy** [comment]
Thanks for taking the time! 🙌 

> Digging deeper it became apparent that it is a bug inside VirtualizedList and it was already fixed in Facebook's RN implementation

Can you point out which upstream version fixed this, if you have that info handy already?

**Comment by pavelchern** [comment]
Hey, yes, sure! 
I browsed the history, it is basically the combination of 
https://github.com/facebook/react-native/commit/515cc6f596ce345fc7591776935d1c56f09cb664#diff-25477c6bad509193f026645fd928dec6 
and 
https://github.com/facebook/react-native/commit/7f2515ece8833f7a8adba025ef544013f89ae26f#diff-25477c6bad509193f026645fd928dec6
at this point

**Review by tom-un — APPROVED** [review]
Thanks!

**Comment by alloy** [comment]
@pavelchern Oof, sorry for letting this sit. Alas there are some conflicts now, would you mind fixing those?

Also, once merged, do you need this in a v0.62.x stable release?

**Comment by pavelchern** [comment]
@alloy, yes, will resolve it today! 

Would be great to include it in the earliest release possible - some people on the `0.60.0-x` would also love to get it so much (but I also hope they upgrade soonish.) 
Would it be possible to backport it to some of the earlier versions as well, what's the process here, are the PRs accepted to these branches?

**Comment by alloy** [comment]
Thanks!

> Would it be possible to backport it to some of the earlier versions as well, what's the process here, are the PRs accepted to these branches?

To target older releases, indeed send a PR targeting those branches. (Will you send one for `0.62-stable`?)

I’m a little more hesitant about back porting fixes to versions that did not have them upstream, although there’s probably no negative impact here so assuming these are absolutely critical to you I’m not opposed to merging them. @tom-un do you have any thoughts on this?

**Comment by pavelchern** [comment]
Sorry for the delay, and thank you @alloy! 

Yes, I have sent a PR against `0.62-stable` here: https://github.com/microsoft/react-native-macos/pull/618 , would appreciate if it can be reviewed as well. 

Regarding back porting to older versions - I will inform the owners of the experiences, but I also hope they are going to migrate to `0.62` pretty soon, so for now I will avoid doing a PR. 
If that appears to be a big problem and critical for them we can maybe revisit it at a later point.

**Comment by alloy** [comment]
@pavelchern Sounds good, thanks for taking the time! 🙏

**Pull request merged**
