### PR TITLE
Fix modal RedBox not running main dispatch queue

### PR DESCRIPTION
**Pull request by appden**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

The RedBox could get an app in a “stuck” state because it would completely pause the main dispatch queue. This was especially evident by changing a style to be an incompatible value (e.g. `width: '50px'`), which would get you in a state where you'd need to just kill and restart the application.

Calling `[NSApp runModalForWindow:]` will result in a new runloop that does not process the main dispatch queue. This change instead runs a modal session on the main runloop that still processes the main dispatch queue.

Further reading:
- https://www.thecave.com/2015/08/10/dispatch-async-to-main-queue-doesnt-work-with-modal-window-on-mac-os-x/
- https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/WinPanel/Concepts/UsingModalWindows.html

## Changelog

[macOS] [Fixed] - Fix modal RedBox not running main dispatch queue

## Test Plan

- Build and run RNTester
- Open `ButtonExample.js`
- Change `flexDirection` to incorrect value (`rows`)
- Observe RedBox modal opens
- Change back to correct value (`row`)
- RedBox disappears and app continues to work

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-macos/pull/609)

### CODE REVIEW

**Comment by appden** [comment]
cc @alloy

**Comment by anandrajeswaran** [comment]
Isn't the bug on whatever is trying to dispatch to the main queue and apparently needs it to respond synchronously in some manner? There is other UI that we'lll want to have on macOS like NSMenus/NSAlerts that hogs the main run loop and we definitely don't want to have to put each of those in its own runloop.

**Review by alloy — APPROVED** [review]
This could possibly be unified with https://github.com/microsoft/react-native-macos/pull/211/commits/b26a0603e770c70f3b83f6fcee729197cc667a8c.

Longer term this should be generic enough to re-use for other windows we want to show modally and contain RN content. @tom-un do we already have something for this or plans?

> Isn't the bug on whatever is trying to dispatch to the main queue and apparently needs it to respond synchronously in some manner?

From my understanding the problem is that we enter this modal session in response to a task that was put on the main queue. This means that from GCD’s perspective a block is already executing on this serial queue and thus no new ones will be executed until the stack completes—thus needing to dispatch to the main thread _outside_ of GCD, allowing the queue task to complete.

> There is other UI that we'lll want to have on macOS like NSMenus/NSAlerts that hogs the main run loop and we definitely don't want to have to put each of those in its own runloop.

iirc we never need to run RN/user code while these controls run modally, so that shouldn’t matter.

**Comment by tom-un** [comment]
> This could possibly be unified with [b26a060](https://github.com/microsoft/react-native-macos/commit/b26a0603e770c70f3b83f6fcee729197cc667a8c).
> 
> Longer term this should be generic enough to re-use for other windows we want to show modally and contain RN content. @tom-un do we already have something for this or plans?
> 
> > Isn't the bug on whatever is trying to dispatch to the main queue and apparently needs it to respond synchronously in some manner?
> 
> From my understanding the problem is that we enter this modal session in response to a task that was put on the main queue. This means that from GCD’s perspective a block is already executing on this serial queue and thus no new ones will be executed until the stack completes—thus needing to dispatch to the main thread _outside_ of GCD, allowing the queue task to complete.
> 
> > There is other UI that we'lll want to have on macOS like NSMenus/NSAlerts that hogs the main run loop and we definitely don't want to have to put each of those in its own runloop.
> 
> iirc we never need to run RN/user code while these controls run modally, so that shouldn’t matter.

@alloy : there are no concrete plans that I know of to add modal support.   macOS has never had an implementation for the Modal component, but it has been Lean Core deprecated and moved to https://github.com/react-native-community/react-native-modal, so if a macOS Modal is created it would be contributed outside of this repo

**Review by tom-un — APPROVED** [review]

**Pull request merged**
