### PR TITLE
[0.66] Fix Integration CI check

### PR DESCRIPTION
**Pull request by Saadnajmi**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

Make whatever changes I need to have the CI pass on the 0.66 branch.

## Changelog

[Internal] [Fixed] - Fix / comment out tests in CI till it passes

### CODE REVIEW

**Comment by acoates-ms** [comment]
Not having a lock file will add to the instability of the builds -- (the build could pick up new versions of pods as they are published with no code change from our side).  Can we instead ensure that the lock file is updated appropriately?

**Comment by Saadnajmi** [comment]
> Not having a lock file will add to the instability of the builds -- (the build could pick up new versions of pods as they are published with no code change from our side). Can we instead ensure that the lock file is updated appropriately?

Removing the lock file in this specific test was suggested by @tido64 here (https://github.com/microsoft/react-native-macos/pull/957#issuecomment-1014255154) where I am trying to fix the test in the main branch. I can see the argument not to remove the lock for a stable branch, since those _could_ be forward compatible. Regardless, that's the lock file in React-Native-Test-App, not react-native-macos

**Comment by Saadnajmi** [comment]
> Not having a lock file will add to the instability of the builds -- (the build could pick up new versions of pods as they are published with no code change from our side). Can we instead ensure that the lock file is updated appropriately?

Or is your suggestion instead to do something like `pod update` instead of `rm podfile.lock`?

**Comment by tido64** [comment]
We can do `pod update`, but we will quickly be updating all packages listed in `Podfile.lock`. The only pods that we need to download are Flipper, DoubleConversion, glog, RCT-Folly, and libevent. Flipper isn't enabled for macOS, and the others are all fixed to an explicit version by react-native. It should be safe to remove `Podfile.lock`.

**Comment by acoates-ms** [comment]
That sounds ok then.

BTW, has anyone looked at enabling flipper in macos?  That seems like something that we should have?

**Comment by Saadnajmi** [comment]
> That sounds ok then.
> 
> BTW, has anyone looked at enabling flipper in macos? That seems like something that we should have?

I've tried running it before but I can't remember if it worked. React Native Test App has it listed as disabled for macOS in their documentation. Once 0.66 is published to NPM, I can give it another try.

**Review by HeyImChris — APPROVED** [review]

**Review by HeyImChris — APPROVED** [review]

**Pull request merged**
