### PR TITLE
[0.73] Fix accessibilityRole

### PR DESCRIPTION
**Pull request by FalseLobster**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary:

During the merge for 0.73, accessibilityRole was accidentally put behind an #if block removing it from macOS's implementation.  This simply restores the functionality of the prop to what it was in 0.72, but more changes are forthcoming to refactor and support the new role prop.

## Changelog:

[MACOS] [FIXED] - Fixed accessibilityRole

## Test Plan:

See before/after of Accessibility Inspector for accessibilityRole="button" changing from AXUnknown to AXButton

Screenshot 2023-12-19 at 12 11 20 PM
Screenshot 2023-12-19 at 12 12 18 PM

### CODE REVIEW

**Review by Saadnajmi — APPROVED** [review]

**Comment by Saadnajmi** [comment]
Thanks for the PR! There’s issues with CI so I might have to force merge it. Can you also prepare the 0.73 version so I can merge both?

**Comment by FalseLobster** [comment]
> Thanks for the PR! There’s issues with CI so I might have to force merge it. Can you also prepare the 0.73 version so I can merge both?

This is the 0.73 PR. Did you mean main?

**Comment by Saadnajmi** [comment]
> > Thanks for the PR! There’s issues with CI so I might have to force merge it. Can you also prepare the 0.73 version so I can merge both?
> 
> 
> 
> This is the 0.73 PR. Did you mean main?

Oh yes, just noticed. Yes, main please. Also for future reference we try to prefix PRs to one of the stable branches with "[0.73] PR title" just so that it's easier to distinguish!

**Comment by FalseLobster** [comment]
> > > Thanks for the PR! There’s issues with CI so I might have to force merge it. Can you also prepare the 0.73 version so I can merge both?
> > 
> > 
> > This is the 0.73 PR. Did you mean main?
> 
> Oh yes, just noticed. Yes, main please. Also for future reference we try to prefix PRs to one of the stable branches with "[0.73] PR title" just so that it's easier to distinguish!

Yea, I just noticed that looking at other PRs. Noted 😅. I'll get the main one out shortly.

**Pull request merged**
