### PR TITLE
Don't install boost twice

### PR DESCRIPTION
**Pull request by Saadnajmi**
#### Please select one of the following
- [x] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [ ] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

There exists `boost` and `boost-for-react-native`, the latter of which was just a copy of boost. RN Core used to use the latter, but stopped doing so with this commit: https://github.com/facebook/react-native/commit/b77948e33bc5e0df422fffca3b4c9253f611d298

We however, kept installing both. We probably shouldn't install boost twice. That should also greatly improve `pod install` times.

## Changelog

[Internal] [Removed] - Removed extra copy of boost

## Test Plan

CI should pass.

### CODE REVIEW

**Comment by Saadnajmi** [comment]
@ZihanChen-MSFT Would you know why the CXX-Turbomodule podspec is failing to build?

**Comment by harrieshin** [comment]
the CI failure seems legit after your boost change

**Comment by Saadnajmi** [comment]
> the CI failure seems legit after your boost change

Agreed, thats why I tested the author of the podspec that fails.

**Review by vmoroz — APPROVED** [review]
:shipit:

**Comment by Saadnajmi** [comment]
This passes now :) , `ScreenshotManager.podspec` did need boost in the header search path

**Review by harrieshin — APPROVED** [review]

**Pull request merged**
