### PR TITLE
Revert "Disable Integration job on main branch"

### LINKED ISSUE #948: [CI] Integration test fails on main
### Environment

```markdown
react-native -v:
npm ls react-native-macos:
node -v:
npm -v:
yarn --version:
xcodebuild -version:
```

### Steps to reproduce the bug

We added a check to our CI called `Integration` that fails on main but passes in `0.64-stable`. We should fix this, bug is to track 

### Expected Behavior

Test passes

### Actual Behavior

Test fails

### Reproducible Demo

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Saadnajmi**
Reverts microsoft/react-native-macos#947
Closes #948

### CODE REVIEW

**Comment by Saadnajmi** [comment]
I'm actually beginning to think the fix might be that react-native-test-app needs to update their own podfile.lock / update their template with react-native-macos 0.66. @tido64 thoughts?

**Review by HeyImChris — APPROVED** [review]

**Comment by tido64** [comment]
> I'm actually beginning to think the fix might be that react-native-test-app needs to update their own podfile.lock / update their template with react-native-macos 0.66. @tido64 thoughts?

Can you add `rm macos/Podfile.lock` before this line: https://github.com/microsoft/react-native-macos/blob/30c55de602d88d6a1df9f0f0bebbc036e2978ac2/.ado/apple-integration.yml#L84

The repo is currently at 0.64. Updating it for 0.66 would break everything else. We need to remove this file regardless because it's not forwards-compatible. I updated the integration script in RNTA, but forgot to do it here as well.

**Comment by Saadnajmi** [comment]
> > I'm actually beginning to think the fix might be that react-native-test-app needs to update their own podfile.lock / update their template with react-native-macos 0.66. @tido64 thoughts?
> 
> Can you add `rm macos/Podfile.lock` before this line:
> 
> https://github.com/microsoft/react-native-macos/blob/30c55de602d88d6a1df9f0f0bebbc036e2978ac2/.ado/apple-integration.yml#L84
> 
> The repo is currently at 0.64. Updating it for 0.66 would break everything else. We need to remove this file regardless because it's not forwards-compatible. I updated the integration script in RNTA, but forgot to do it here as well.

Thanks.

**Comment by Saadnajmi** [comment]
The latest CI run fails from the familiar `clockid_` redefinition error, which we fixed in RN-macOS with a [postinstall script](https://github.com/microsoft/react-native-macos/blob/65f2be82e651138dd2eae02cec7751b325f5afce/template/ios/Podfile#L26 ) in our template po file while we wait for @amgleitman 's [fix in folly](https://github.com/facebook/folly/pull/1688) to merge.

We can probably add that script into RNTA (though I recall RNTA removing all their postinstall scripts recently so they may not want that), but it does make me think of the question of dependencies again. With every RN-macOS release, will this check only pass once we've published a stable version package and RNTA has had a chance to update themselves? If so, should we keep it disabled on `main` where we may not be in a supported state?

**Comment by tido64** [comment]
> The latest CI run fails from the familiar `clockid_` redefinition error, which we fixed in RN-macOS with a [postinstall script](https://github.com/microsoft/react-native-macos/blob/65f2be82e651138dd2eae02cec7751b325f5afce/template/ios/Podfile#L26) in our template po file while we wait for @amgleitman 's [fix in folly](https://github.com/facebook/folly/pull/1688) to merge.
> 
> We can probably add that script into RNTA (though I recall RNTA removing all their postinstall scripts recently so they may not want that), but it does make me think of the question of dependencies again. With every RN-macOS release, will this check only pass once we've published a stable version package and RNTA has had a chance to update themselves? If so, should we keep it disabled on `main` where we may not be in a supported state?

Sorry for the inconvenience. Ideally, fixes like this should be hidden behind the one post-install script, `react_native_post_install`. I dunno why we decided to add another one that users have to go and add themselves. I've been advocating for more seamless upgrades, things like this keep going through. Let me add the script real quick.

**Comment by Saadnajmi** [comment]
> > The latest CI run fails from the familiar `clockid_` redefinition error, which we fixed in RN-macOS with a [postinstall script](https://github.com/microsoft/react-native-macos/blob/65f2be82e651138dd2eae02cec7751b325f5afce/template/ios/Podfile#L26) in our template po file while we wait for @amgleitman 's [fix in folly](https://github.com/facebook/folly/pull/1688) to merge.
> 
> Sorry for the inconvenience. Ideally, fixes like this should be hidden behind the one post-install script, `react_native_post_install`. I dunno why we decided to add another one that users have to go and add themselves. I've been advocating for more seamless upgrades, but things like this keep going through. Let me add the script real quick.
> 
> Edit: https://github.com/microsoft/react-native-test-app/pull/704
> 
> > We can probably add that script into RNTA (though I recall RNTA removing all their postinstall scripts recently so they may not want that), but it does make me think of the question of dependencies again. With every RN-macOS release, will this check only pass once we've published a stable version package and RNTA has had a chance to update themselves? If so, should we keep it disabled on `main` where we may not be in a supported state?
> 
> I wouldn't be so quick to throw this out. This isn't a required run so it failing doesn't block anyone. If the red-X is annoying, we can probably reduce it to a warning. However, it has caught many real issues and I think it would be better if we could be pro-active rather than reactive about fixing them.

I didn't notice it was not required, thank you :D. I agree not to throw it out, my apologies :). I wanted to understand the dependency graph better, and having it fail so we can be proactive makes total sense!

**Comment by Saadnajmi** [comment]
@tido64 Any idea why the "validate manifest" script phase fails?

**Comment by tido64** [comment]
> @tido64 Any idea why the "validate manifest" script phase fails?

It's a new thing I added to make sure that `app.json` is valid. It looks like it fails to run on Node 12. Sorry about that.

**Comment by tido64** [comment]
Filed #975

**Pull request merged**
