### PR TITLE
Use border radius when drawing focus rings

### PR DESCRIPTION
**Pull request by appden**
### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

For rounded (or partially rounded) buttons, the focus ring would still draw being square. This change allows for focus rings to respect the corner radii.

## Changelog

[macOS] [Fixed] - Use border radius when drawing focus rings

## Test Plan

Focus rings draw circular now with border radius. Also confirmed square focus rings for views without border radius set.

Screen Shot 2020-11-15 at 6 02 54 PM

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-macos/pull/652)

### CODE REVIEW

**Comment by alloy** [comment]
Just a heads-up that we’re looking into the CI failure. /cc @tom-un

**Comment by tom-un** [comment]
> Just a heads-up that we’re looking into the CI failure. /cc @tom-un Tom Underhill FTE

I have a fix for the broken CI failure here: https://github.com/microsoft/react-native-macos/pull/654.   Once its lands in master you just have to re-merge master to this PR.

**Comment by alloy** [comment]
> > Just a heads-up that we’re looking into the CI failure. /cc @tom-un Tom Underhill FTE
> 
> I have a fix for the broken CI failure here: #654. Once its lands in master you just have to re-merge master to this PR.

This landed. @appden mind merging/rebase master?

**Comment by appden** [comment]
@alloy I rebased. Thanks!

**Review by alloy — APPROVED** [review]

**Pull request merged**
