### PR TITLE
Deprecate `acceptsKeyboardFocus`

### PR DESCRIPTION
**Pull request by Saadnajmi**
#### Please select one of the following
- [x] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [ ] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

`focusable` replaced the prop `acceptsKeyboardFocus` back in 0.63, but we never deprecated or removed it. Let's remove it now.

## Changelog

[macOS] [Removed] - Removed the prop `acceptsKeyboardFocus`

## Test Plan

Testing that the keyboarding events test page in RNTester still works should be enough. I also looked downstream and didn't see anyone still using this prop.

### CODE REVIEW

**Comment by HeyImChris** [comment]
If we never deprecated `acceptsKeyboardFocus` I'm not sure we can comfortably remove it all at once. Did you verify downstream clients aren't using it? We shouldn't drop support for an API without some warning or deprecation notice to clients first, but if you've done that then I'm on board for getting rid of this.

**Comment by Saadnajmi** [comment]
> If we never deprecated `acceptsKeyboardFocus` I'm not sure we can comfortably remove it all at once. Did you verify downstream clients aren't using it? We shouldn't drop support for an API without some warning or deprecation notice to clients first, but if you've done that then I'm on board for getting rid of this.

We can deprecate it this release, and remove it next release. Downstream I did not see anyone using it, since react native windows/win32 already deprecated and removed it by 0.64.

I'll update this PR to be a deprecation.

**Comment by NickGerleman** [comment]
@acoates-ms ended up being the one to deal with a lot of the fallout for the NetUI transition to focusable. We did it too quickly there, but it's been longer for macOS, and I would expect most xplat code to also now be on focusable.

**Comment by Saadnajmi** [comment]
> I added a change to make acceptsKeyboardFocus yellowbox at the same time as I added focusable support. https://github.com/microsoft/react-native-macos/pull/655

Yeah, I saw that PR. I kinda just wanted to skip the yellowbox altogether because I'm pretty sure nobody is using acceptsKeyboardFocus anymore. It's probably best to be proper and deprecate in one release before removing it in the next.

**Comment by NickGerleman** [comment]
What kind of depreciation were you looking at? This is what react-native-macos has been saying since 0.63: '"acceptsKeyboardFocus" has been deprecated in favor of "focusable" and will be removed in a future version of react-native-macos'

**Comment by Saadnajmi** [comment]
> What kind of depreciation were you looking at? This is what react-native-macos has been saying since 0.63: '"acceptsKeyboardFocus" has been deprecated in favor of "focusable" and will be removed in a future version of react-native-macos'

Oh sorry, I confused PRs. I was thinking about how in RNW, the yellowbox was turned to a Redbox but not necessarily removed. 

Somehow I didn't realize we were already yellowboxing. That makes me more happy to just delete it altogether 🤣.

**Comment by Saadnajmi** [comment]
> We should be sure to mention this in the next RN-macOS update as removing an API can always have client fallout (even if it's been deprecated for over a year).

If we're planning to have some release notes / generate a changeless, probably a good thing to call out!

**Comment by Saadnajmi** [comment]
@acoates-ms My (unrelated) change to Pressable in RN-Win32 removed `acceptsKeyboardFocus` and broke things for LPC downstream. Given I don't want to repeat that experience here, should I not merge this change / keep it only for 0.66+ ?

**Pull request merged**
