### PR TITLE
Add Tooltip support

### PR DESCRIPTION
**Pull request by chiuam**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [ ] I am making a fix / change for the macOS implementation of react-native
- [X] I am making a change required for Microsoft usage of react-native

## Summary
This change adds tooltip support for the following components:
1. Button
2. Text
3. Image
4. Slider
5. TextInput

## Changelog

[CATEGORY] [TYPE] - Message

## Test Plan
image

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-macos/pull/701)

### CODE REVIEW

**Comment by HeyImChris** [comment]
Are there any other controls that might need this? For instance macOS sliders have a tooltip to represent the % it's set to. Checkboxes also have tooltips and so can TextInputs on macOS. If we can easily enough get them all up and running that'd probably save us some time in the future

**Comment by chiuam** [comment]
> Are there any other controls that might need this? For instance macOS sliders have a tooltip to represent the % it's set to. Checkboxes also have tooltips and so can TextInputs on macOS. If we can easily enough get them all up and running that'd probably save us some time in the future

Sure, I added tooltip support to slider and text input. I think Checkbox has been removed from React Native and has a community module for it now - https://github.com/react-native-community/react-native-checkbox

**Comment by HeyImChris** [comment]
Run `yarn flow-check-ios` and you'll see a couple JS issues that'll need to get fixed up. Once that command is all green then it should be good to checkin.

**Comment by HeyImChris** [comment]
I tried cloning your branch and making this change myself but I don't have permissions to push to your fork (probably a good thing :)).  You'll want to add `onPress={() => {}}` on line `63` in Button.js under `tooltip={"Button tooltip"}` for the CI errors to go away- then we can check in!

**Review by HeyImChris — APPROVED** [review]

**Pull request merged**
