### PR TITLE
scroll content with animation

### PR DESCRIPTION
**Pull request by marty-wang**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

This PR fixes the issue where the scrollbar does not move/animate when scrollToOffset/End is called.

## Changelog

[macOS] [Fixed] - Fixes the issue where the scrollbar does not move/animate when scrollToOffset/End is called

## Test Plan

https://user-images.githubusercontent.com/1132214/107857810-9afad400-6de5-11eb-942a-0fff9dc5b693.mov

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-macos/pull/725)

### CODE REVIEW

**Review by appden — APPROVED** [review]

**Review by alloy — APPROVED** [review]
Perhaps the magic number used as duration could be moved to the top of the file, but otherwise the change seems good to me 👍 

One thing that would worry me slightly is the whitespace changes, which may make it harder to merge in upstream changes in the future, but I’ll defer to @HeyImChris on that.

**Review by HeyImChris — APPROVED** [review]

**Comment by HeyImChris** [comment]
Just a heads up this failed the CI with an error that we intermittently hit. Very confident it's unrelated to your change so I kicked off another build that will hopefully succeed and then we can merge this in

**Comment by HeyImChris** [comment]
> Perhaps the magic number used as duration could be moved to the top of the file, but otherwise the change seems good to me 👍
> 
> One thing that would worry me slightly is the whitespace changes, which may make it harder to merge in upstream changes in the future, but I’ll defer to @HeyImChris on that.

I agree that it'd be great to move all constants to the top. As for the whitespace... it's definitely a noble change. Maybe we can make the same whitespace fixes upstream too so we don't hit merge problems later? @marty-wang

**Comment by marty-wang** [comment]
> > Perhaps the magic number used as duration could be moved to the top of the file, but otherwise the change seems good to me 👍
> > One thing that would worry me slightly is the whitespace changes, which may make it harder to merge in upstream changes in the future, but I’ll defer to @HeyImChris on that.
> 
> I agree that it'd be great to move all constants to the top. As for the whitespace... it's definitely a noble change. Maybe we can make the same whitespace fixes upstream too so we don't hit merge problems later? @marty-wang

will do

**Review by harrieshin — APPROVED** [review]

**Comment by appden** [comment]
Btw, this fixes #706

**Comment by HeyImChris** [comment]
> Btw, this fixes #706

Thanks- merged!

**Pull request merged**
