### PR TITLE
Fix insertion point and placeholder placement for TextInput

### PR DESCRIPTION
**Pull request by christophpurrer**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

This fixes issues where the insertion point (caret) would not initially render in the correct location for `TextInput` with padding. Also, for single-line inputs, the placeholder would also be in the wrong location.

## Changelog

[macOS] [Fixed] - Fix insertion point and placeholder placement for TextInput

## Test Plan

Set a padding of 10
```
    padding: 10,
```

### Before

You *must* click to put the caret/insertionPointer in the correct location

https://user-images.githubusercontent.com/484044/182496667-9b1fe28c-dcfb-4c3f-9402-14f676c90205.mov

### After

https://user-images.githubusercontent.com/484044/182496605-ddbc5b0e-8add-4ad6-a7dc-d7d946a51854.mov

### CODE REVIEW

**Comment by chiuam** [comment]
I think this change broke the auto-focus test case:

https://user-images.githubusercontent.com/67026167/183540352-f366bb68-856f-4760-9077-6a631e9d5fdc.mov

> *** Assertion failure in -[RCTTouchHandler _recordNewTouches:](), /Users/amchiu/react-native-macos/React/Base/RCTTouchHandler.m:110
2022-08-08 21:00:41.054210-0400 RNTester-macOS[81288:6998379] [General] Touch is already recorded. This is a critical bug.

**Comment by christophpurrer** [comment]
Thanks for pointing this out. That's indeed an issue. We don't have atm as we also changed RTCTouchHandler.
I think I need to wait on this change and see if I can upstream some of our changes to RTCTouchHandler

**Comment by Saadnajmi** [comment]
Don't close

**Comment by Saadnajmi** [comment]
Gonna stop marking these where they get stale...

**Comment by christophpurrer** [comment]
The latest iteration fixes the problem for the RCTTouchHandler by applying another band-aid solution.
However in the long term we need to find a better approach to correctly handle mouseUp events.
Maybe the
```
_shouldSendMouseUpOnSystemBehalf
```
BOOL approach is not the best one.

We have a large number RCTTouchHandler fixes - but also those are not yet in a state to upstream them ...


https://user-images.githubusercontent.com/484044/187002042-4927ba94-958f-4e6e-aa68-a74289128ea4.mov

**Comment by Saadnajmi** [comment]
@chiuam could you take a second look?

**Review by chiuam — APPROVED** [review]

**Pull request merged**
