### PR TITLE
[chore] cleanup the markdown files

### PR DESCRIPTION
**Pull request by kelset**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [x] I am making a change required for Microsoft usage of react-native

## Summary

I was starting to work on a doc with a more clear git flow between upstream and this fork, and I realized that a few things could have been tackled. So I'm opening this PR separately to just do the cleanups, and leave the git flow doc work for a separate one.

Here's an overview of some of the things that I've cleaned up:
* I've removed the two root level Changelog files since they are useless. We should address the lack of release notes and changelog, but not in this PR.
* removed the upstream Code of Conduct: the one we use as Microsoft is different, and it is mentioned in the README. So removing the upstream file for consistency.
* ~updated the wording in the LICENSE file to match what we say in the readme AND match what is in the [RNW repo](https://github.com/microsoft/react-native-windows/blob/main/LICENSE) - I'm pretty sure the fact that it wasn't matching the RNW one was an oversight, I'm trying to get confirmation.~
  * see further comment for details on why this was reverted
* removed the ecosystem markdown, it's an upstream thing not relevant for us.
* moved all the other markdowns files in the `/docs` folder
* cleaned up the README to be less verbose, certain things were written multiple times. ([preview](https://github.com/microsoft/react-native-macos/blob/758694ecd3b19215ae52de176fb0b5173c2bd3cf/README.md))

## Test Plan

N/A

### CODE REVIEW

**Review by Saadnajmi — APPROVED** [review]
Thanks! Something else I just remembered that @NickGerleman mentioned that could fit in this PR-> changing the description on our root level package.json. Currently it says:
> "description": "[Microsoft Fork] A framework for building native apps using React",

Looking at the [React Native Windows](https://github.com/microsoft/react-native-windows/blob/main/vnext/package.json) one, something as simple as "React Native for macOS" might be sufficient?
>  "description": "React Native for Windows", 

Not a big deal! Just remembered it now

**Review by HeyImChris — APPROVED** [review]
Is the ReadMe cleanup mostly aligning the verbose parts with what's upstream? Good chance any diffs you make that aren't easily identifiable as macOS specific would get overwritten in the next merge.

**Comment by kelset** [comment]
> Is the ReadMe cleanup mostly aligning the verbose parts with what's upstream? Good chance any diffs you make that aren't easily identifiable as macOS specific would get overwritten in the next merge.

@HeyImChris in a way, the README becomes more custom so the rule of thumb should be (for this and all other .md files) that we ignore the upstream changes entirely. Only exception should be in the licence when we'll change from Facebook to Meta Inc.

**Comment by kelset** [comment]
re: the LICENSE file. I've asked the OSPO team and their guideline is that we need to keep the upstream license untouched and verify with CELA contact if that's correct. So for the sake of getting this merged, I'm reverting the License change and that should be tackled separately.

**Review by chrisHogan — APPROVED** [review]

**Pull request merged**
