### PR TITLE
[0.64] Pull in upstream fixes to expose hover props on Pressable #884

### PR DESCRIPTION
**Pull request by Saadnajmi**
Same as #884 except targeting the 0.64-stable branch.

### CODE REVIEW

**Comment by acoates-ms** [comment]
This looks like a breaking change?  Shouldnt we support the old property names (with warning) for a period of time to allow apps to transition?

**Comment by Saadnajmi** [comment]
> This looks like a breaking change? Shouldnt we support the old property names (with warning) for a period of time to allow apps to transition?

Right, I wanted opinions about that. The "old" property names (onMouseEnter/onMouseLeave) didn't actually work until #855 which was 22 days ago. I assume nobody has actually gone and used the old property names in the last 22 days. However, react-native-windows explicitly supports both for backwards compatible, which is why I added @rectified95 / @NickGerleman to ask their opinions about supporting both. 

I can pull in the changes from react-native-windows to support both onMouseEnter/onMouseLeave AND onHoverIn/onHoverOut, but if nobody is using the former, we can reduce diffs by not supporting it.

**Comment by acoates-ms** [comment]
My opinion:
If it wasn't available in 0.63, then we can probably assume people are not using them.
There isn't need to support properties that react-native-windows supported.  - Its fine to just support the new ones.

**Comment by Saadnajmi** [comment]
> My opinion:
> If it wasn't available in 0.63, then we can probably assume people are not using them.
> There isn't need to support properties that react-native-windows supported. - Its fine to just support the new ones.

It's available in the very latest 0.63.x release with #857 . I think it's safe to assume the only person possibly using it was me at the time.

**Comment by acoates-ms** [comment]
So it was in one dot release, maybe you can do the rename in 0.63 too.. So its not around for long.  Otherwise people on 0.63 might start using it before switching to 0.64?

**Comment by Saadnajmi** [comment]
@acoates-ms That's fair, I can make a 3rd PR to pull this into 0.63-stable as well.

**Review by HeyImChris — APPROVED** [review]

**Comment by Saadnajmi** [comment]
Closing in favor of #922

**Pull request closed without merging**
