### PR TITLE
Pull in upstream fixes to expose hover props on Pressable

### PR DESCRIPTION
**Pull request by Saadnajmi**
#### Please select one of the following
- [x] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [ ] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

In https://github.com/facebook/react-native/pull/32405 , I exposed the props `onHoverIn / onHoverOut` on Pressable. This change brings the same 

## Changelog

[General] [Fixed] - Pressable not passing hover props and event handlers to PressabilityConfig

## Test Plan

Updated pressable test page in rn-tester

### CODE REVIEW

**Comment by rectified95** [comment]
I know this is already upstream, but I'm wondering how onHoverin/out is different from mouseEnter/Leave

**Comment by Saadnajmi** [comment]
> I know this is already upstream, but I'm wondering how onHoverin/out is different from mouseEnter/Leave

I think the name difference is Microsoft and Facebook independently adding mouse support for different scenarios:
Facebook for react-native-web, Microsoft for our desktop forks. Poking around in react-native-windows, it looks like we added onMouseEnter/onMouseLeave, then when Facebook added onHoverIn/onHoverOut , rn-windows decided to support both in Pressability. For my FHL a few weeks ago, I was trying to figure out how to align the hover props across RN Core / windows / macOS, and I mostly landed on just following facebooks' onHoverIn & onHoverOut naming and making sure we followed that for rn-macos

**Comment by acoates-ms** [comment]
Its interesting that Facebook went with a different naming scheme than the web APIs, which is what we copied the onMouseEnter API after.   Having said that, I do prefer the non input specific API.  -- Its more like what we moved to in windows with pointerEntered.

**Comment by Saadnajmi** [comment]
> Its interesting that Facebook went with a different naming scheme than the web APIs, which is what we copied the onMouseEnter API after. Having said that, I do prefer the non input specific API. -- Its more like what we moved to in windows with pointerEntered.

I think it's also something to do with `Pressable` trying to be a little more platform agnostic than `View`, At the end of the day `Pressable` just wraps a `View` component, and forwards the `onHoverIn` event handler as an `onMouseEnter` event handler to `View`. The benefit of Pressable is it handles extra details like `delayHoverIn` / whatever else.

**Comment by acoates-ms** [comment]
Yup, my guess is that a gaze gesture in VR might trigger onHoverIn etc.  This is why I like the input agnostic naming.  The web APIs were designed a long time ago back before computers had so many input modalities.

**Review by HeyImChris — APPROVED** [review]

**Review by harrieshin — APPROVED** [review]

**Pull request merged**
