### PR TITLE
Include building and publishing with Android NDKr21 into PR and publi…

### PR DESCRIPTION
**Pull request by mganandraj**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native :thumbsup:
- [ ] I am making a fix / change for the macOS implementation of react-native
- [x] I am making a change required for Microsoft usage of react-native

Devmain is being switched to using Android NDK r21. This change adds PR valiation for building using NDK r21 and publish job using NDK r21.

#### Focus areas to test
No change in product code. Ensure PR jobs succeeds.. and ensure that a nuget package built with NDK r21 is published whose version is appended with '-ndk21'

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native/pull/321)

### CODE REVIEW

**Comment by acoates-ms** [comment]
Is the new android publish going to overwrite the other one?  It looks like both jobs are putting the build artifacts in the same place.  I think they will end up overwriting each other.  And maybe get a race condition on which one will end up getting published.  Should you remove the old version?

**Comment by mganandraj** [comment]
> Is the new android publish going to overwrite the other one? It looks like both jobs are putting the build artifacts in the same place. I think they will end up overwriting each other. And maybe get a race condition on which one will end up getting published. Should you remove the old version?

Andrew.. We are appending "-ndk${version}" to the nuget version when built with new pipeline  .. and i believe that will rename the package file name too .. And the new task doesn't publish JS code... There may still be a race condition as both jobs writes the outputs to the same directory .. Let me fix that by changing the output path of the new pipeline..

We may want to keep the old pipeline around until the devmain has completely switched .. Whether the ndk21 built react-native binaries work with ndk16 built office binaries is not tested ..

**Comment by acoates-ms** [comment]
@mganandraj  - do we still need this PR?  Or can we close it?

**Comment by mganandraj** [comment]
> @mganandraj - do we still need this PR? Or can we close it?

Sure .. It can be closed ..

**Pull request closed without merging**
