### PR TITLE
AB#5845915 Adding a yaml-to-script script to convert pr yaml files into local sc…

### PR DESCRIPTION
**Pull request by rasaha91**
…ripts

#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [ ] I am making a fix / change for the macOS implementation of react-native
- [x] I am making a change required for Microsoft usage of react-native

## Summary

Trying to build for Android locally is cumbersome because it involves copying the steps from android-pr.yml to a local script and executing commands one at a time, substituting template parameter values and working directories appropriately. To make things less annoying, I wrote a small CLI to generate this script for you, performing the necessary substitutions as needed. The user is also allowed to select which commands they wish to keep in the script.

Run `scripts/yaml-to-script.sh --help` for usage details. 

## Changelog

[Android] [Added] - Adding a script to convert a yaml pr file to a local script

## Test Plan

This doesn't affect ReactNative, and instead helps improve the inner dev loop for those working on Android.

### CODE REVIEW

**Comment by rasaha91** [comment]
Example execution of generated script:

image

Example of summary at end of script execution:
image

**Comment by kelset** [comment]
I'm not a big fan of adding extra packages to a fork - does it need to live here? Can't it live somewhere else, like rnx-kit?

**Comment by rasaha91** [comment]
Testing out email response - can you explain what you mean by 'extra packages'? I don't get how it's different than adding any other script to the scripts folder. The project only gets built for those who use the script. I don't really care where it lives - just curious about why the current location is frowned upon.

________________________________

**Comment by kelset** [comment]
@rasaha91 :
> can you explain what you mean by 'extra packages'?
This PR adds a new package to the monorepo (yaml-to-script/package.json)

This codebase is a fork, so adding extra code that is not relevant to the fork just add noise.

Also, I am not sure how email notification work for GH but I've edited my comment a couple times, so maybe open the PR in the browser to see my latest feedback?

**Comment by rasaha91** [comment]
> @rasaha91 :
> 
> > can you explain what you mean by 'extra packages'?

> 
> Also, I am not sure how email notification work for GH but I've edited my comment a couple times, so maybe open the PR in the browser to see my latest feedback?

Yes, it seems that github emails don't notify you of edits - probably to reduce noise. 

> 
> This PR adds a new package to the monorepo (`yaml-to-script/package.json`)
> 
> This codebase is a fork, so adding extra code that is not relevant to the fork just add noise.

Ah, I thought you were referring to the node modules that the script consumes. Wasn't familiar with the terminology of package in that context. Sure, I agree that this repo should be bare minimal.

Regarding your point about why not make it a bash script. I was thinking of the general case where there are some commands you may need to run locally, but some only for PR purposes (e.g renaming the package), and the order of execution matters. In that case, there isn't a single bash script you could write (well technically you could, with a param that gets passed in to specify if its a local build or not). With this tool, I wrote it to be pretty generic to ado pipelines, and nothing really specific to this repo. If for instance I wanted to execute the commands for another pipeline at some point, I don't want to refactor that yaml file, just so I can emulate that pipeline. To be clear, although this package solves the problem of building for android locally, the package was authored to be more general than that. If you think it shouldn't be in any RN related repo at all, I'm happy to keep it in my personal repo and others can consume it if desired.

As a side point, I also think we should refactor some of the logic in the yaml file to make it clear which steps should not be run locally. This was something I talked to Anandraj about.

**Comment by kelset** [comment]
> the package was authored to be more general than that.

if that's the case then I'd probably argue it'd be better to place it in rnx-kit. That said, I still think it's probably worth exploring the refactoring of the yaml first

**Comment by rasaha91** [comment]
> > the package was authored to be more general than that.
> 
> if that's the case then I'd probably argue it'd be better to place it in rnx-kit. That said, I still think it's probably worth exploring the refactoring of the yaml first

Sure I can move it to rnx-kit... although I was under the impression that people were hesitant against putting non rn stuff in there. While related, I wasn't sure if this would be a welcome addition there. 

Refactoring the yml is on my list of things to do, however it will require some thought. I do like how the PR breaks down individual tasks so you can see failures at a granular level, rather than just getting "your large bash script that does everything failed". Sifting through a massive log sucks. So anyways, still thinking about the best thing to do there.

**Comment by rasaha91** [comment]
@kelset I discussed with @afoxman offline and it seems that rnx-kit is not an appropriate location for such a tool. As such I'm just going to keep this in my personal tools repo I have (rasaha91/rnandroid-devtools) and people can consume it as desired. @mganandraj as FYI (let me know if you have a preferred shared location for this tool)

**Comment by rasaha91** [comment]
Moved to my personal devtools repo. Abandoning this PR.

**Pull request closed without merging**
