### PR TITLE
Fix a few v0.62 issues

### LINKED ISSUE #553: Issues after app migration to 0.62 prerelease
### Environment

1. `react-native -v`: 0.62.2
3. `npm ls react-native-macos`: 0.62.0-prerelease.6
4. `node -v`: 14.7.0
5. `npm -v`: 6.14.4
6. `yarn --version` 1.22.4
7. `xcodebuild -version`: 11E708

### Issue

1. I had to rename `Folly` pod to [`RCT-Folly`](https://github.com/microsoft/react-native-macos/blob/master/third-party-podspecs/RCT-Folly.podspec) which is not a part of the unforked RN update guide:
    * https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.2
    * https://raw.githubusercontent.com/react-native-community/rn-diff-purge/release/0.62.2/RnDiffApp/ios/Podfile

2. I was not able to build the app because of missing header file in [RCTRedBox.mm#L17](https://github.com/microsoft/react-native-macos/blob/master/React/CoreModules/RCTRedBox.mm#L17):
```[...]/react-native-macos/React/CoreModules/RCTRedBox.mm:17:9: 'React/RCTRedBoxExtraDataViewController.h' file not found```

    Those files are exclusively excluded for macOS [React-Core.podspec#L66](https://github.com/microsoft/react-native-macos/blob/master/React-Core.podspec#L66), but this change was a part of `0.61` which was building and working as expected for me. 

    Removing the exclusion from the `podspec` locally and reinstalling pods won't fix the issue.

3. After removing or commenting out the code parts related to the `RCTRedBoxExtraDataViewController` from the `RCTRedBox.mm` Xcode failed to launch the Metro bundler because of missing permissions:
Screenshot 2020-08-19 at 17 58 02

`chmod +X launchPackager.command` won't help, I had to use `chmod 777 launchPackager.command`.

4. The same permission problem occurred with `react-native-xcode.sh` script:
```/[...]/macos/DerivedData/Reminders/Build/Intermediates.noindex/Reminders.build/Debug/Reminders-macOS.build/Script-381D8A6E24576A4E00465D17.sh: line 3: ../node_modules/react-native-macos/scripts/react-native-xcode.sh: Permission denied```

After dealing with all the issues listed above locally I was able to build and run app using `0.62` prerelease version 🙂 

### Steps to Reproduce

1. Clone `https://github.com/Simek/react-native-macos-reminders.git`
2. Switch to `0.62` branch
3. Open `macos/Reminders.xworkspace` in Xcode
4. Build or launch the app

### Expected Behavior

Build succeeded and app running without issues (like on `0.61`).

### Actual Behavior

Build fails.

### Reproducible Demo

* https://github.com/Simek/react-native-macos-reminders

### Additional context

AMA

### PR DESCRIPTION
**Pull request by alloy**
Fixes #553 

See the commit messages.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/react-native-macos/pull/560)

### CODE REVIEW

**Comment by alloy** [comment]
Oh, looks like a PR needs to be approved by at least 1 person with push access; you don’t have push access, @harrieshin ?

**Comment by harrieshin** [comment]
i don't. please add me @tom-un  :)

**Comment by harrieshin** [comment]
> Oh, looks like a PR needs to be approved by at least 1 person with push access; you don’t have push access, @harrieshin ?

i currently don't. Please add me! @tom-un  (i wonder @HeyImChris has permission to grant me. but he is oof)

**Comment by acoates-ms** [comment]
@harrieshin - Just added you to the write group.

**Pull request merged**
