### PR TITLE
Fix animation bug 

### PR DESCRIPTION
**Pull request by chiuam**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [X] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary
I'm working on a FURN control https://github.com/microsoft/fluentui-react-native/pull/669 that uses the animated library, and there's a bug where animation doesn't loop when the native driver is enabled. There's already a fix https://github.com/facebook/react-native/pull/29585 for the bug but it hasn't been merged to upstream. I want to bring in this fix into our fork to unblock my work.

## Changelog

[Apple] [Bug] - bug fix for Animated

## Test Plan
Tested the animation logic in RNTester, I was able to repro the bug and verified that the change fixes the bug.

### CODE REVIEW

**Review by Saadnajmi — APPROVED** [review]

**Comment by harrieshin** [comment]
don't forget that you might need to merge these changes in .63 and .62 branches

**Review by harrieshin — APPROVED** [review]

**Comment by harrieshin** [comment]
should there be a test case in the tester app?

**Comment by Saadnajmi** [comment]
Maybe mark with the TODO markers since it is a difference from upstream currently? And @harrieshin I think adding a test case will cause more react-native core/macOS divergence

**Comment by chiuam** [comment]
> should there be a test case in the tester app?

Actually we already have a test case for looping animation in the Native Animated Example page, the bug didn't surface there probably because the shimmer animation uses a hook instead.

**Comment by harrieshin** [comment]
> > should there be a test case in the tester app?
> 
> Actually we already have a test case for looping animation in the Native Animated Example page, the bug didn't surface there probably because the shimmer animation uses a hook instead.

should we extend the test case so that it has an example that uses the hook then?

**Comment by chiuam** [comment]
> > > should there be a test case in the tester app?
> > 
> > 
> > Actually we already have a test case for looping animation in the Native Animated Example page, the bug didn't surface there probably because the shimmer animation uses a hook instead.
> 
> should we extend the test case so that it has an example that uses the hook then?

I think that'd be helpful, but the scope might be bigger than I thought so let's do a followup on it.

**Pull request merged**
