### PR TITLE
Fix build errors with codegen discovery flag enabled

### PR DESCRIPTION
**Pull request by shwanton**
#### Please select one of the following
- [ ] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [x] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

Although fabric is not supported on RN Desktop, the codegen aspect of turbomodules should work correctly.

Building RNTester with the `USE_CODEGEN_DISCOVERY=1` flag was throwing errors.

build command: `USE_CODEGEN_DISCOVERY=1 bundle exec pod install;`

```
[Codegen] Done.
TypeError [ERR_INVALID_ARG_TYPE]: The "args" argument must be of type object. Received type string ('/Users/shawndempsey/src/...)
    at new NodeError (node:internal/errors:372:5)
    at normalizeSpawnArguments (node:child_process:515:11)
    at execFileSync (node:child_process:854:13)
    at /Users/shawndempsey/src/shwanton_react-native-macos/scripts/generate-artifacts.js:238:7
    at Array.forEach (<anonymous>)
    at main (/Users/shawndempsey/src/shwanton_react-native-macos/scripts/generate-artifacts.js:211:15)
    at Object.<anonymous> (/Users/shawndempsey/src/shwanton_react-native-macos/scripts/generate-artifacts.js:322:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

There was a change made to `generate-artifacts` d68d2095e92cf7b29113d40bef68ab05568a1884 that refactored usage to `execFileSync`. The error is thrown because `execFileSync` expects an [array as it's second argument](https://nodejs.org/api/child_process.html).

## Changelog

[macOS] [Revert] Revert "Use execFileSync over execSync when messing with file paths in generate-artifacts.js"
[macOS] [Fix] Don't try and build Fabric example when USE_CODEGEN_DISCOVERY=1

### Build RNTester w/ flag

`USE_CODEGEN_DISCOVERY=1 bundle exec pod install`

*ScreenshotManager Native TurboModule should work from JS*

https://user-images.githubusercontent.com/96719/182487353-a97f4252-beb4-4e74-abc3-c3e64bac6bba.mp4

### CODE REVIEW

**Comment by Saadnajmi** [comment]
@Shwanton Do you know if this change would work on RN-macOS 0.68? Considering whether it's worth back porting.

**Comment by shwanton** [comment]
@Saadnajmi I tested this on the 0.68 branch so will work fine.

**Comment by Saadnajmi** [comment]
@amgleitman Could you take a second look at this? I worry about the changes of `execFileSync -> execSync` because security.

**Comment by Saadnajmi** [comment]
@shwanton `execSync` is more vulnerable to malformed input moreso than `execFileSync`, which is why we made the original change. Any chance you can refactor this to use `execFileSync`?

**Comment by shwanton** [comment]
Yes, I'll refactor to use `execFileSync` & call w/ correct args.

**Comment by shwanton** [comment]
@Saadnajmi Updated to use `execFileSync`!

**Review by mischreiber — APPROVED** [review]

**Pull request merged**
