### PR TITLE
Use yarn format to format native code [WIP]

### PR DESCRIPTION
**Pull request by christophpurrer**
#### Please select one of the following
- [x] I am removing an existing difference between facebook/react-native and microsoft/react-native-macos :thumbsup:
- [ ] I am cherry-picking a change from Facebook's react-native into microsoft/react-native-macos :thumbsup:
- [ ] I am making a fix / change for the macOS implementation of react-native
- [ ] I am making a change required for Microsoft usage of react-native

## Summary

Like ```yarn prettier --fix``` for JS code, we should also run ```yarn format``` for native code.
Ideally this would also run as CI job > Who can help on that task?
See also: https://reactnative.dev/contributing/how-to-contribute-code#development-workflow

I did some quick tests, and the result seems identical to the one used in facebook/react-native

Note: We need to make sure to have the same repo-config which has been (partially) addressed in https://github.com/microsoft/react-native-macos/pull/1333

If we use the same native code-style between facebook/react-native and microsoft/react-native-macos it should also make merges, rebases and cherry-picking easier

## Changelog

[macOS] [Fixed] - Use yarn format to format native code

## Test Plan

Ran ```yarn format``` no further changes.
Style of changes matches facebook/react-native, e.g. order of imports sorted or ```*_Nullable``` vs ```* _Nullable```

### CODE REVIEW

**Comment by Saadnajmi** [comment]
Would it be ok if I add commits to this PR to make it part of our CI checks? I didn't notice that React Native Core had a clang format check, thanks!

**Comment by Saadnajmi** [comment]
If I compare this branch against RN Core's 0.68-stable branch (as compared to RN-macOS master vs RN Core @ 0.68-stable), the number of file diffs goes up from 840 to ~908. Do you happen to know why? I imagine formatting our code would reduce diffs between RN-macOS and RN Core

I compare branches by "pretending" to make a PR to RN Core's 0.68-stable. Let me know if you have a better way to do this.
https://github.com/facebook/react-native/compare/0.68-stable...christophpurrer:react-native-macos:format?expand=1

**Comment by christophpurrer** [comment]
Something is in-deed not working here. Although both repros have the same .clang-format
- https://github.com/microsoft/react-native-macos/blob/main/.clang-format
- https://github.com/facebook/react-native/blob/main/.clang-format
... the results are not identical.

Some of the changes seem to align the files with facebook/react-native - others do it.
I need to follow up internally and update this PR once I have figured out the 'right' setting

**Comment by christophpurrer** [comment]
There are some Meta changes needed, before this PR can land.
- facebook/react-native is not running .clang-format on CircleCI builds
- facebook/react-native is not using the .clang-format checked in the repro
We plan to address to both issues. Stay tuned

**Comment by christophpurrer** [comment]
At Meta we don't auto-format native (C++/ObjC) atm. And if we would do (according our coding style) it would touch 13334 lines of code. That would actually mean more merge conflicts for this repo - *except* you also run the same formatter rules before the next merge ....

I'll abandon for now and maybe we can revisit this topic later on.
Ideally we would be able to just write code and auto-format via command line or IDE, no matter if it is JS or native code

**Pull request closed without merging**
